#!/bin/bash

rm -fr AppDir

(
make distclean
qmake
make -j7
)

rm -f linuxdeploy*.AppImage

wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

chmod +x linuxdeploy*.AppImage

./linuxdeploy-x86_64.AppImage  \
    --appdir AppDir/   \
    -d Simul6.desktop  \
    -i images/appicon.svg  \
    -e bin/simul6b  \
    --output appimage \
    --plugin qt \

