#!/bin/bash

rm -fr AppDir

(
make distclean
qmake
make -j7
)

rm -f linuxdeploy*.AppImage Simul6-*-x86_64.AppImage

wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

chmod +x linuxdeploy*.AppImage

./linuxdeploy-x86_64.AppImage  \
    --appdir AppDir/   \
    -d Simul6.desktop  \
    -i images/appicon.svg  \
    -e bin/simul6  \
    --output appimage \
    --plugin qt \

VERSION=$(cat version.pri | awk -F '"' '$1 ~ "APP_VERSION" { print $2; }')
mv -f Simul6-*-x86_64.AppImage Simul6-$VERSION-x86_64.AppImage

